# Generated by Django 4.2.11 on 2024-03-23 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_analyst_inventory_organism_role_sample_sampletype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='role_name',
        ),
        migrations.RemoveField(
            model_name='role',
            name='role_permissions',
        ),
        migrations.AddField(
            model_name='analyst',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyst', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
