# Generated by Django 4.2.11 on 2024-03-23 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_role_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='specimen',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='type',
        ),
        migrations.RemoveField(
            model_name='sampleresults',
            name='analyst',
        ),
        migrations.RemoveField(
            model_name='sampleresults',
            name='reagent',
        ),
        migrations.RemoveField(
            model_name='sampleresults',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='sampleresults',
            name='test',
        ),
        migrations.RemoveField(
            model_name='specimen',
            name='organism',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Organism',
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
        migrations.DeleteModel(
            name='SampleResults',
        ),
        migrations.DeleteModel(
            name='SampleType',
        ),
        migrations.DeleteModel(
            name='Specimen',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
