# Generated by Django 4.2.11 on 2024-04-02 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_sample_specimen_remove_sample_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyst',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyst', to=settings.AUTH_USER_MODEL),
        ),
    ]
