# Generated by Django 4.2.11 on 2024-03-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimen',
            name='sample_name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='cohort',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
