# Generated by Django 4.2.11 on 2024-03-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labdata', '0002_specimen_sample_name_alter_specimen_cohort_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='sample_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
