# Generated by Django 4.2.11 on 2024-04-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labdata', '0005_alter_test_reportable_results'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleresults',
            name='reagent',
        ),
        migrations.AddField(
            model_name='sampleresults',
            name='reagents',
            field=models.ManyToManyField(related_name='sample_results', to='labdata.inventory'),
        ),
    ]
