# Generated by Django 4.2.11 on 2024-04-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labdata', '0006_remove_sampleresults_reagent_sampleresults_reagents'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimen',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='specimen',
            name='race',
            field=models.CharField(blank=True, choices=[('W', 'White'), ('B', 'Black or African American'), ('A', 'Asian'), ('H', 'Hispanic or Latino'), ('N', 'American Indian or Alaska Native'), ('O', 'Native Hawaiian or Other Pacific Islander'), ('U', 'Unknown or Not Reported')], default='', max_length=1),
        ),
    ]
